#!/usr/bin/bash

set -e

prefix=$(cat prefix)
supdir="${prefix}/Superpowers"
mkdir -p "${supdir}"
# I have no clue what really needs to be copied…
cp -a core "${supdir}"
cp -a app "${supdir}"
find "${supdir}" -type d -a -name '.git' -print0 | xargs -0 rm -rf

bindir="${prefix}/bin"
mkdir -p "${bindir}"
escapedsupdir=$(echo "${supdir}" | sed -e 's/[\/&]/\\&/g')
sed -ie "s/@SUPDIR@/${escapedsupdir}/g" run-superpowers
cp -a run-superpowers "${bindir}"
